// Centralized mock data and RBAC definitions for the Admin Portal
export const roleDefinitions = {
  guest: {
    name: "Guest",
    description: "Khách truy cập website",
    permissions: ["catalog.read", "promotions.read"],
    modules: ["Homepage", "Models", "Compare", "Promotions", "Test Drive Request", "Get Quote", "Track Order"],
    color: "bg-gray-100 text-gray-800",
  },
  customer: {
    name: "Customer",
    description: "Khách hàng đã đăng ký",
    permissions: [
      "catalog.read",
      "promotions.read",
      "testdrives.create",
      "quotes.create",
      "payments.initiate",
      "orders.read",
      "complaints.create",
    ],
    modules: ["Account", "Orders", "Test Drives", "Track Order", "Documents"],
    color: "bg-blue-100 text-blue-800",
  },
  dealer_staff: {
    name: "Dealer Staff",
    description: "Nhân viên bán hàng đại lý",
    permissions: [
      "catalog.read",
      "inventory.read",
      "customers.read",
      "customers.create",
      "customers.update",
      "testdrives.read",
      "testdrives.create",
      "quotes.read",
      "quotes.create",
      "quotes.submit",
      "orders.read",
      "orders.create",
      "payments.read",
      "allocations.create",
      "complaints.read",
      "reports.read.self",
    ],
    modules: ["Dashboard", "Customers", "Test Drives", "Quotes", "Orders", "Inventory", "CRM", "Reports"],
    color: "bg-green-100 text-green-800",
  },
  dealer_manager: {
    name: "Dealer Manager",
    description: "Quản lý đại lý",
    permissions: [
      "quotes.approve",
      "quotes.reject",
      "orders.approve",
      "orders.cancel",
      "inventory.manage",
      "payments.capture",
      "payments.refund",
      "promotions.create",
      "settings.users.read",
      "reports.read.dealer",
    ],
    modules: ["Dashboard", "Approvals", "Inventory Management", "Pricing", "Staff Management", "Reports", "Settings"],
    color: "bg-purple-100 text-purple-800",
  },
  evm_staff: {
    name: "EVM Staff",
    description: "Nhân viên nhà sản xuất",
    permissions: [
      "catalog.manage",
      "pricing.manage",
      "inventory.manage",
      "allocations.approve",
      "shipments.create",
      "promotions.create",
      "dealers.read",
      "dealers.manage",
      "reports.read.global",
    ],
    modules: [
      "Product Catalog",
      "Global Inventory",
      "Dealer Management",
      "Pricing & Promotions",
      "Allocation & Shipments",
      "Reports & Analytics",
    ],
    color: "bg-orange-100 text-orange-800",
  },
  admin: {
    name: "Admin",
    description: "Quản trị hệ thống",
    permissions: ["settings.users.manage", "settings.integrations.manage", "settings.policies.manage", "audit.read"],
    modules: ["System Settings", "User Management", "Integrations", "Security", "Audit Logs", "System Monitoring"],
    color: "bg-red-100 text-red-800",
  },
} as const

export const stateMachines = {
  quote: {
    states: ["Draft", "Submitted", "Approved", "Rejected", "Expired", "Converted"],
    transitions: {
      Draft: ["Submitted"],
      Submitted: ["Approved", "Rejected"],
      Approved: ["Converted", "Expired"],
      Rejected: ["Draft"],
      Expired: [],
      Converted: [],
    },
  },
  order: {
    states: ["Draft", "Confirmed", "Production", "Ready", "Delivered", "Cancelled"],
    transitions: {
      Draft: ["Confirmed", "Cancelled"],
      Confirmed: ["Production", "Cancelled"],
      Production: ["Ready", "Cancelled"],
      Ready: ["Delivered"],
      Delivered: [],
      Cancelled: [],
    },
  },
  payment: {
    states: ["Pending", "Authorized", "Captured", "Failed", "Refunded", "Cancelled"],
    transitions: {
      Pending: ["Authorized", "Failed", "Cancelled"],
      Authorized: ["Captured", "Cancelled"],
      Captured: ["Refunded"],
      Failed: ["Pending"],
      Refunded: [],
      Cancelled: [],
    },
  },
  testdrive: {
    states: ["Requested", "Confirmed", "Completed", "NoShow", "Cancelled"],
    transitions: {
      Requested: ["Confirmed", "Cancelled"],
      Confirmed: ["Completed", "NoShow", "Cancelled"],
      Completed: [],
      NoShow: [],
      Cancelled: [],
    },
  },
} as const

export const approvalThresholds = {
  discount: {
    auto_approve: 5,
    manager_approve: 10,
    evm_approve: 100,
  },
  payment: {
    manager_capture: 50_000_000,
    admin_capture: 999_999_999,
  },
} as const

export const inventoryData = [
  {
    id: "VF001",
    model: "VF8",
    variant: "Eco",
    color: "Xanh Đại Dương",
    vin: "VF8ECO2024001",
    status: "available",
    price: 1_200_000_000,
    location: "Showroom Quận 1",
    dealer_id: "DEALER_001",
    allocated_to: null,
    eta: null,
    importDate: "2024-01-02",
  },
  {
    id: "VF002",
    model: "VF9",
    variant: "Plus",
    color: "Trắng Ngọc Trai",
    vin: "VF9PLUS2024002",
    status: "reserved",
    price: 1_500_000_000,
    location: "Showroom Quận 7",
    dealer_id: "DEALER_001",
    allocated_to: null,
    eta: null,
    importDate: "2024-01-05",
  },
  {
    id: "VF003",
    model: "VF6",
    variant: "Base",
    color: "Đỏ Ruby",
    vin: "VF6BASE2024003",
    status: "sold",
    price: 750_000_000,
    location: "Showroom Thủ Đức",
    dealer_id: "DEALER_002",
    allocated_to: null,
    eta: null,
    importDate: "2023-12-25",
  },
  {
    id: "VF004",
    model: "VF7",
    variant: "Base",
    color: "Xám Titan",
    vin: "VF7BASE2024004",
    status: "maintenance",
    price: 990_000_000,
    location: "Xưởng dịch vụ",
    dealer_id: "DEALER_001",
    allocated_to: null,
    eta: null,
    importDate: "2024-01-08",
  },
]

export const testDriveBookings = [
  {
    id: "TD001",
    customerName: "Nguyễn Văn A",
    phone: "0901234567",
    email: "nguyenvana@email.com",
    model: "VF8",
    variant: "Plus",
    date: "2024-01-15",
    time: "10:00",
    showroom: "Showroom Quận 1",
    status: "confirmed",
    assigned_staff: "S001",
    dealer_id: "DEALER_001",
    notes: "Khách quan tâm màu xanh",
  },
  {
    id: "TD002",
    customerName: "Trần Thị B",
    phone: "0902345678",
    email: "tranthib@email.com",
    model: "VF9",
    variant: "Plus",
    date: "2024-01-16",
    time: "14:30",
    showroom: "Showroom Quận 7",
    status: "requested",
    assigned_staff: "S002",
    dealer_id: "DEALER_001",
    notes: "Cần tư vấn về tùy chọn pin",
  },
  {
    id: "TD003",
    customerName: "Lê Văn D",
    phone: "0903456789",
    email: "levand@email.com",
    model: "VF6",
    variant: "Base",
    date: "2024-01-17",
    time: "09:00",
    showroom: "Showroom Thủ Đức",
    status: "completed",
    assigned_staff: "S003",
    dealer_id: "DEALER_002",
    notes: "Khách hàng hài lòng",
  },
]

export const quotes = [
  {
    id: "Q001",
    customerName: "Trần Thị B",
    phone: "0902345678",
    email: "tranthib@email.com",
    model: "VF9",
    variant: "Plus",
    color: "Trắng Ngọc Trai",
    basePrice: 1_500_000_000,
    discount: 75_000_000,
    discountPercent: 5,
    finalPrice: 1_425_000_000,
    status: "approved",
    validUntil: "2024-02-15",
    createdBy: "S001",
    approvedBy: "M001",
    dealer_id: "DEALER_001",
    accessories: ["Bộ phụ kiện thể thao", "Camera 360"],
    promotions: ["Khuyến mãi tết 2024"],
  },
  {
    id: "Q002",
    customerName: "Nguyễn Văn A",
    phone: "0901234567",
    email: "nguyenvana@email.com",
    model: "VF8",
    variant: "Eco",
    color: "Xanh Đại Dương",
    basePrice: 1_200_000_000,
    discount: 120_000_000,
    discountPercent: 10,
    finalPrice: 1_080_000_000,
    status: "submitted",
    validUntil: "2024-02-20",
    createdBy: "S001",
    approvedBy: null,
    dealer_id: "DEALER_001",
    accessories: ["Thảm lót sàn cao cấp"],
    promotions: ["Ưu đãi khách hàng VIP"],
  },
  {
    id: "Q003",
    customerName: "Phạm Thị C",
    phone: "0904567890",
    email: "phamthic@email.com",
    model: "VF7",
    variant: "Base",
    color: "Đỏ Ruby",
    basePrice: 990_000_000,
    discount: 0,
    discountPercent: 0,
    finalPrice: 990_000_000,
    status: "draft",
    validUntil: "2024-02-25",
    createdBy: "S002",
    approvedBy: null,
    dealer_id: "DEALER_001",
    accessories: [],
    promotions: [],
  },
]

export const orders = [
  {
    id: "ORD001",
    quoteId: "Q001",
    customerName: "Trần Thị B",
    phone: "0902345678",
    model: "VF9",
    variant: "Plus",
    color: "Trắng Ngọc Trai",
    totalPrice: 1_425_000_000,
    depositPaid: 142_500_000,
    remainingAmount: 1_282_500_000,
    status: "confirmed",
    orderDate: "2024-01-10",
    expectedDelivery: "2024-03-15",
    assignedStaff: "S001",
    dealer_id: "DEALER_001",
    allocation_status: "requested",
    contract_status: "pending",
    payment_status: "partial",
  },
  {
    id: "ORD002",
    quoteId: "Q002",
    customerName: "Nguyễn Văn A",
    phone: "0901234567",
    model: "VF8",
    variant: "Eco",
    color: "Xanh Đại Dương",
    totalPrice: 1_080_000_000,
    depositPaid: 108_000_000,
    remainingAmount: 972_000_000,
    status: "draft",
    orderDate: "2024-01-12",
    expectedDelivery: "2024-03-10",
    assignedStaff: "S001",
    dealer_id: "DEALER_001",
    allocation_status: "not_requested",
    contract_status: "pending",
    payment_status: "pending",
  },
]

export const salesStaff = [
  {
    id: "S001",
    name: "Lê Văn C",
    email: "levanc@vinfast.vn",
    phone: "0903456789",
    role: "dealer_staff",
    showroom: "Showroom Quận 1",
    dealer_id: "DEALER_001",
    monthlyTarget: 10,
    currentSales: 7,
    status: "active",
  permissions: [...roleDefinitions.dealer_staff.permissions],
    manager_id: "M001",
  },
  {
    id: "S002",
    name: "Phạm Thị D",
    email: "phamthid@vinfast.vn",
    phone: "0904567890",
    role: "dealer_staff",
    showroom: "Showroom Quận 7",
    dealer_id: "DEALER_001",
    monthlyTarget: 15,
    currentSales: 12,
    status: "active",
  permissions: [...roleDefinitions.dealer_staff.permissions],
    manager_id: "M001",
  },
  {
    id: "M001",
    name: "Hoàng Văn E",
    email: "hoangvane@vinfast.vn",
    phone: "0905678901",
    role: "dealer_manager",
    showroom: "Tất cả showroom",
    dealer_id: "DEALER_001",
    monthlyTarget: 50,
    currentSales: 35,
    status: "active",
    permissions: [...roleDefinitions.dealer_staff.permissions, ...roleDefinitions.dealer_manager.permissions] as string[],
    manager_id: null,
  },
]

export const promotions = [
  {
    id: "PROMO001",
    name: "Khuyến mãi Tết 2024",
    description: "Giảm giá đặc biệt dịp Tết Nguyên Đán",
    discountType: "percentage",
    discountValue: 5,
    scope: "global",
    applicableModels: ["VF8", "VF9"],
    startDate: "2024-01-01",
    endDate: "2024-02-29",
    status: "active",
    budget: 5_000_000_000,
    used: 1_200_000_000,
    createdBy: "EVM001",
    dealer_id: null,
    usageCount: 100,
    maxUsage: 500,
  },
  {
    id: "PROMO002",
    name: "Ưu đãi khách hàng VIP",
    description: "Chiết khấu đặc biệt cho khách hàng thân thiết",
    discountType: "fixed",
    discountValue: 50_000_000,
    scope: "dealer",
    applicableModels: ["VF6", "VF7", "VF8", "VF9"],
    startDate: "2024-01-15",
    endDate: "2024-12-31",
    status: "active",
    budget: 1_000_000_000,
    used: 300_000_000,
    createdBy: "M001",
    dealer_id: "DEALER_001",
    usageCount: 50,
    maxUsage: 200,
  },
]

export const reportingData = {
  salesByMonth: [
    { month: "T10/2024", sales: 45, revenue: 54_000_000_000 },
    { month: "T11/2024", sales: 52, revenue: 62_400_000_000 },
    { month: "T12/2024", sales: 67, revenue: 80_400_000_000 },
    { month: "T1/2025", sales: 19, revenue: 22_800_000_000 },
  ],
  salesByModel: [
    { model: "VF 6", sales: 89, percentage: 38.5 },
    { model: "VF 7", sales: 67, percentage: 29.0 },
    { model: "VF 8", sales: 52, percentage: 22.5 },
    { model: "VF 9", sales: 23, percentage: 10.0 },
  ],
  salesByShowroom: [
    { showroom: "Showroom Quận 1", sales: 78, revenue: 93_600_000_000 },
    { showroom: "Showroom Quận 7", sales: 65, revenue: 78_000_000_000 },
    { showroom: "Showroom Thủ Đức", sales: 45, revenue: 54_000_000_000 },
    { showroom: "Showroom Bình Thạnh", sales: 43, revenue: 51_600_000_000 },
  ],
  conversionFunnel: [
    { stage: "Website Visits", count: 12_450, percentage: 100 },
    { stage: "Test Drive Bookings", count: 1_245, percentage: 10 },
    { stage: "Quote Requests", count: 623, percentage: 5 },
    { stage: "Orders Placed", count: 231, percentage: 1.85 },
    { stage: "Delivered", count: 183, percentage: 1.47 },
  ],
}
